/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajout_reclamation (void);
GtkWidget* create_gestion_reclamation (void);
GtkWidget* create_modifier_reclamation (void);
GtkWidget* create_statistique_reclamation (void);
